apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo2"
  description: "demo2"
  tags:
    - sx-cnp-oss
    - template
    - metalstack
  links:
    - url: https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Grafana SRE Metrics
      icon: web
  annotations:
    github.com/project-slug: AntoniusUIBK/Demo2
    backstage.io/kubernetes-id: demo2
    kubecost.com/deployment-name: demo2
    argocd/app-name: demo2
    backstage.io/kubernetes-namespace: uibklab-demo2
    backstage.io/kubernetes-label-selector: app=demo2
    kubevirt-manager: "https://kubevirt-manager.lab.suxessit.k8s.cloud.uibk.ac.at/"
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> 'kubevirt')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=&var-namespace=test-demo-kubevirt&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "uibklab"
  system: demo2
  dependsOn:
    - resource:argocd
    - resource:kubevirt
    - resource:kubecost
    - resource:k8s-monitoring
    - resource:kubevirt-manager
    - resource:kubevirt
    - resource:loki
