
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo2
  description: Demo2
  labels:
    stage: test
    platform-engineer.cloud/creator: backstage-template
spec:
  team: uibklab
